// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9dPDOA3i9sDxJt1o-SNWr5eQm-THDNa8',
    appId: '1:113092505912:web:71e048a7cb1926968391cd',
    messagingSenderId: '113092505912',
    projectId: 'museum-tugasakhir',
    authDomain: 'museum-tugasakhir.firebaseapp.com',
    storageBucket: 'museum-tugasakhir.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgH8YAGM5mND3GY87_7c1P_hZiI1bgOs0',
    appId: '1:113092505912:android:bd9a1568b1dab1e08391cd',
    messagingSenderId: '113092505912',
    projectId: 'museum-tugasakhir',
    storageBucket: 'museum-tugasakhir.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXB4VpypbXUzlzawA7-Z30VX4Ojiaj3r4',
    appId: '1:113092505912:ios:6783f8413c9579998391cd',
    messagingSenderId: '113092505912',
    projectId: 'museum-tugasakhir',
    storageBucket: 'museum-tugasakhir.firebasestorage.app',
    iosBundleId: 'com.example.museumTugasakhir',
  );

}